### ISSUE TITLE
Palworld doesn't trigger Auto HDR

### ISSUE THREAD

**Issue by RyanRoff97** [7gxycn08/ForceAutoHDR#1]
Hi, I followed the directions and added the exe file for this game into the ForceAutoHDR app register. It was under steamapps. I've tried launching the game multiple times, but it still will not engage Auto HDR, which I'm a bit sad about. I have Auto HDR working in other games just fine too.

**Comment by RyanRoff97** [comment]
Forcing Auto HDR works on the Xbox version, but not the Steam version. Really hope you an fix this! I'll be so happy, thanks!

**Comment by 7gxycn08** [comment]
> Forcing Auto HDR works on the Xbox version, but not the Steam version. Really hope you an fix this! I'll be so happy, thanks!

Did you follow number 4 of the instructions?

"To make sure AutoHDR Is working open Xbox Game Bar open HDR Intensity Slider and move it around If the brightness keeps shifting means It's working."

Windows 11 will not notify you that AutoHDR is working however when you move the Intensity slider In Gamebar you should notice the brightness shifting that indicates that it's working.

**Comment by RyanRoff97** [comment]
Yes, I did. But when I try to move the Adjust HDR intensity slider, it just stays there and does not move. It is all the way to the right, so it is maxed out. The Xbox version does not have this issue and HDR works fine on that one thanks to this program. No idea why the Steam version is still in SDR. I'm even playing the game and on Xbox it's clear Auto HDR is doing a great job, but on Steam it's just SDR. I added the right exe file as well for the Steam version. I may try the GOG version to see if that works unless you are able to somehow fix the Steam version not working with Auto HDR.

**Comment by 7gxycn08** [comment]
> Yes, I did. But when I try to move the Adjust HDR intensity slider, it just stays there and does not move. It is all the way to the right, so it is maxed out. The Xbox version does not have this issue and HDR works fine on that one thanks to this program. No idea why the Steam version is still in SDR. I'm even playing the game and on Xbox it's clear Auto HDR is doing a great job, but on Steam it's just SDR. I added the right exe file as well for the Steam version. I may try the GOG version to see if that works unless you are able to somehow fix the Steam version not working with Auto HDR.

Make sure your adding the correct exe in the program for the steam version if you can screenshot the game folder i can tell you which one. 

Usually there are two exe files one is in the main game directory the other one is inside another directory.

**Comment by 7gxycn08** [comment]
Steam Version Works Normally Just Tested.
![Screenshot 2024-01-20 223212](https://github.com/7gxycn08/ForceAutoHDR/assets/121936658/94272c35-4b76-476d-8661-c0f212df7483)

**Comment by RyanRoff97** [comment]
![Palworld 1_20_2024 5_03_20 PM](https://github.com/7gxycn08/ForceAutoHDR/assets/157229679/04108a4a-ef0c-43ca-b185-6be81c6ce1bf)
This was the directory I used

**Comment by RyanRoff97** [comment]
> Steam Version Works Normally Just Tested. ![Screenshot 2024-01-20 223212](https://private-user-images.githubusercontent.com/121936658/298301234-94272c35-4b76-476d-8661-c0f212df7483.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3OTkzODQsIm5iZiI6MTcwNTc5OTA4NCwicGF0aCI6Ii8xMjE5MzY2NTgvMjk4MzAxMjM0LTk0MjcyYzM1LTRiNzYtNDc2ZC04NjYxLWMwZjIxMmRmNzQ4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMVQwMTA0NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGQ1MzdkMDczMDllNTk3ZWEyZGIwNDBjNTEwYWEyZDQ5YzczODMwNTRiNGIzMTE5M2U2YzQwNjEyYzRlZWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z1Ghka9y4UMPfi7Oro9lbrrx953HR3F8iPLjlwprhJE)

I'll try this thanks. Also, it says Windows Security found a trojan on my computer anytime I download the app you have for ForceAutoHDR. No idea why.  
![Windows Security 1_20_2024 5_08_23 PM](https://github.com/7gxycn08/ForceAutoHDR/assets/157229679/89eda5f1-8572-45e8-8595-89cc2a2e065c)

Should I ignore and keep the file?

**Comment by RyanRoff97** [comment]
It worked! Thanks very much. NOw, I'm still considered about this trojan on my PC from downloading the file. As you see in the pic, I'm not sure what to do. Is it a false positive?

**Comment by 7gxycn08** [comment]
> It worked! Thanks very much. NOw, I'm still considered about this trojan on my PC from downloading the file. As you see in the pic, I'm not sure what to do. Is it a false positive?

Yes it's a false positive since the program is not digitally signed windows defender will flag it.
You can check with a firewall it does not make any connections to the Internet.
