### ISSUE TITLE
This is unrelated. But ForceDisableAutoHDR?

### ISSUE THREAD

**Issue by SnabbSpelare** [7gxycn08/ForceAutoHDR#10]
### ForceDisableAutoHDR

Would it be possible to reverse this by a **ForceDisableAutoHDR** feature or additional program?
I mean that'd probably be pretty useless in most titles you can disable the **AutoHDR** feature in like in **Battlefield 1**.

_But a worthy idea? What do you think?_

**Comment by 7gxycn08** [comment]
You can disable AutoHDR switch from windows settings. Settings > Display > Graphics.

![autohdrdisable](https://github.com/user-attachments/assets/b313a40b-7a9d-4a07-8b0b-d998aca24af0)
