### ISSUE TITLE
Idea for a new Tool: AutoHDR brightness changer

### ISSUE THREAD

**Issue by Neko14789** [7gxycn08/ForceAutoHDR#2]
Hi, I saw the types of programs you made on GitHub, do you think you would know how to make a tray app similar to monitorian (https://github.com/emoacht/Monitorian) or twinkle tray (https://github.com/xanderfrangos/twinkle-tray), but instead of changing monitor brightness allow changing the autohdr brightness (the slider you can change when going into settings -> system -> monitor -> Use HDR -> Brightness for HDR-Content)?

**Comment by 7gxycn08** [comment]
> Hi, I saw the types of programs you made on GitHub, do you think you would know how to make a tray app similar to monitorian (https://github.com/emoacht/Monitorian) or twinkle tray (https://github.com/xanderfrangos/twinkle-tray), but instead of changing monitor brightness allow changing the autohdr brightness (the slider you can change when going into settings -> system -> monitor -> Use HDR -> Brightness for HDR-Content)?

Are you talking about this slider?

![Screenshot 2024-01-23 200712](https://github.com/7gxycn08/ForceAutoHDR/assets/121936658/21976de5-6d37-49f2-9286-241df00394c4)

**Comment by Neko14789** [comment]
One source I found that touches this request is this https://stackoverflow.com/questions/74594751/controlling-sdr-content-brightness-programmatically-in-windows-11

**Comment by Neko14789** [comment]
> > Hi, I saw the types of programs you made on GitHub, do you think you would know how to make a tray app similar to monitorian (https://github.com/emoacht/Monitorian) or twinkle tray (https://github.com/xanderfrangos/twinkle-tray), but instead of changing monitor brightness allow changing the autohdr brightness (the slider you can change when going into settings -> system -> monitor -> Use HDR -> Brightness for HDR-Content)?
> 
> Are you talking about this slider?
> 
> ![Screenshot 2024-01-23 200712](https://private-user-images.githubusercontent.com/121936658/299013418-21976de5-6d37-49f2-9286-241df00394c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjY0NTYsIm5iZiI6MTcwNjAyNjE1NiwicGF0aCI6Ii8xMjE5MzY2NTgvMjk5MDEzNDE4LTIxOTc2ZGU1LTZkMzctNDlmMi05Mjg2LTI0MWRmMDAzOTRjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QxNjA5MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmIxM2YxMDhmMGQ0MWRiOWU0ZTAyMDQ5MjE3Nzg0M2I1MjViMzliMGNlNTMxOWRiZDhmYjEyM2I0ODNiYzRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W8IdMCRo5trlKveOmyl9Bmc7WjozZLvdLeMvw02LfQE)

Yes

**Comment by 7gxycn08** [comment]
> > > Hi, I saw the types of programs you made on GitHub, do you think you would know how to make a tray app similar to monitorian (https://github.com/emoacht/Monitorian) or twinkle tray (https://github.com/xanderfrangos/twinkle-tray), but instead of changing monitor brightness allow changing the autohdr brightness (the slider you can change when going into settings -> system -> monitor -> Use HDR -> Brightness for HDR-Content)?
> > 
> > 
> > Are you talking about this slider?
> > ![Screenshot 2024-01-23 200712](https://private-user-images.githubusercontent.com/121936658/299013418-21976de5-6d37-49f2-9286-241df00394c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjY0NTYsIm5iZiI6MTcwNjAyNjE1NiwicGF0aCI6Ii8xMjE5MzY2NTgvMjk5MDEzNDE4LTIxOTc2ZGU1LTZkMzctNDlmMi05Mjg2LTI0MWRmMDAzOTRjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QxNjA5MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmIxM2YxMDhmMGQ0MWRiOWU0ZTAyMDQ5MjE3Nzg0M2I1MjViMzliMGNlNTMxOWRiZDhmYjEyM2I0ODNiYzRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W8IdMCRo5trlKveOmyl9Bmc7WjozZLvdLeMvw02LfQE)
> 
> Yes, my system is in German language, so I did not 100% know the wording of the setting in English.

Will do some research to see if it can be controlled programmatically.

**Comment by 7gxycn08** [comment]
Not possible without reverse engineering windows. There is no api to interact with `SDR content brightness`.
It's possible though through GUI automation but it's not a clean solution.

**Comment by 7gxycn08** [comment]
> I thought it was this one instead ![image](https://private-user-images.githubusercontent.com/9145512/299182387-e7d364ca-dd18-4002-bbf8-510832ba3424.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzIzNjcsIm5iZiI6MTcwNjA3MjA2NywicGF0aCI6Ii85MTQ1NTEyLzI5OTE4MjM4Ny1lN2QzNjRjYS1kZDE4LTQwMDItYmJmOC01MTA4MzJiYTM0MjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjRUMDQ1NDI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjkxNDg5YzA2ZDljZGVjM2UzOWFiYmJkOTg1YmM5NWRlMmEyNTcyODc4ZDMxZmUwZTE2ZjA3NTdhYjZmZDg2NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5FPWxTDtnKwNVwXT6vmrccxQyDleIRGMEayTPOr0Zgo)

This slider affects Auto HDR white levels. That one is for SDR when HDR is enabled.
