### ISSUE TITLE
Program adds Enshrouded as nshrouded in registry

### ISSUE THREAD

**Issue by pitrako** [7gxycn08/ForceAutoHDR#3]
It ignores the E on Enshrouded.

**Comment by 7gxycn08** [comment]
Need more info.

Can you give an example of a processes name?

**Comment by 7gxycn08** [comment]
was able to replicate will fix in next release.

**Comment by 7gxycn08** [comment]
Fixed In  [v1.0.0.1](https://github.com/7gxycn08/ForceAutoHDR/releases/tag/v1.0.0.1)
