### ISSUE TITLE
Games with forced AutoHDR have "weird" colors in 24H2 with Nvidia drivers 560.94

### ISSUE THREAD

**Issue by ipisano** [7gxycn08/ForceAutoHDR#9]
I know this is not an issue with the tool itself, but I'm trying to gather information / feedback.
I used to be able to force AutoHDR, but now I get weird colors. I'm honestly not sure if what broke it was the Windows update or a Nvidia driver update, cause games whitelisted by MS still work with AutoHDR, the issue is just when I force it, and the game I used to use this tool/tweak for has been officially added to the whitelist in 24H2. One weird thing I noticed, is that when I opened the tool I couldn't find my previously added games. I added a new game and I noticed the issue, so I tried with a  couple more and sure enough the issue was present in those as well. Is it possible that Microsoft changed around the structure / keys required to force AutoHDR?

Also, before anyone tells me to use RTX HDR, NVTrueHDR, SpecialK, Reshade etc... RTX HDR doesn't work with dual monitors, NVTrueHDR is finnicky and I don't like what it does with colour saturation in some games, SpecialK and Reshade can't be used with some of the titles I want to because of anticheat/injection issues. AutoHDR was a simple, set and forget, "good enough" solution.

**Comment by 7gxycn08** [comment]
Do all games exhibit "weird" colors or just a specific games?

**Comment by ipisano** [comment]
All games not "natively" supported by AutoHDR. However, I found this settings page which I'm not sure was present in older Windows 11 versions like 23H2 (more precisely, I think this page by itself is not new but the per-game AutoHDR switch is)
![ApplicationFrameHost_KqWrNUBFCl](https://github.com/user-attachments/assets/aae828a4-46fc-4513-917b-447361e3138f)
Apparently, it allows you to toggle AutoHDR manually for each game (provided you enable the main AutoHDR switch), and every game has it enabled even though I'm sure they didn't support AutoHDR officially (at least before the 24H2 update).
Can anyone with an older version check if that setting/switch is available?

I came across an **extremely** puzzling behaviour:

- I had success forcing AutoHDR in this game before (23H2 with older Nvidia drivers). I'm 100% sure this game needed the extra registry keys present for AutoHDR to work (again, in 23H2).

- I checked the registry and I have no key for this game anymore to force AutoHDR (as I specified in my earlier post, all the keys in Computer\HKEY_CURRENT_USER\Software\Microsoft\Direct3D were wiped (by the 24H2 update?) 

- I launched the game, with the AutoHDR switch enabled as pictured (but no registry keys). The Intensity Slider from Game Bar can be adjusted but it doesn't have any effect, and AutoHDR is not working. 

- I used your tool to create the registry keys, disabled the AutoHDR switch (in the window of the screenshot, wish I didn't do this step), launched the game and had the same behaviour I described before with the intensity bar being adjustable but no effect. My reasoning for disabling the switch was, maybe the weird colors were because AutoHDR was being applied twice?

- Finally, I re-enabled the switch and I was able to get AutoHDR working properly.

I could try with the two other games I was having the weird colors issues with (specifically, Wuthering Waves and Atomic Heart, those were the only two games I tried forcing AutoHDR on in 24H2), but getting Nvidia's HDR implementation to work with my multi monitor setup was hard and I don't want to repeat the process in case I can't get AutoHDR to work with them. I'll be testing with more games in the following days, but at this point I believe there's some kinda trickery going on involving the per-game switch shown in the screenshot.

**Comment by 7gxycn08** [comment]
This Toggle is there if you want to enable/disable Auto HDR for some games It **doesn't** enable Auto HDR if the **registry keys are not present**. This Toggle doesn't apply AutoHDR twice if it's enabled. It's there to give you more control.


[[](url)](https://private-user-images.githubusercontent.com/18221957/360178981-aae828a4-46fc-4513-917b-447361e3138f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTQ0OTAsIm5iZiI6MTcyNDMxNDE5MCwicGF0aCI6Ii8xODIyMTk1Ny8zNjAxNzg5ODEtYWFlODI4YTQtNDZmYy00NTEzLTkxN2ItNDQ3MzYxZTMxMzhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA4MDk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjYzU0OWIwN2UwOTdhZDkzNjllNTI3ZWEyMzIwMDQzNmViYWRmODJiZDZiNDAwNjViYmNiNjdlNDgxYmRiNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i7Y9bqr91ZM7u2tHkQI71n8BFd8iPO_Lo4sHlxsGuec)

Just tested the game in your list 1000xResist and added the registry keys for AutoHDR there are no "weird" colors.

**Comment by 7gxycn08** [comment]
There is an open issue on FeedBackHub https://aka.ms/AAs31iz
Microsoft is looking into it.

**Comment by 7gxycn08** [comment]
Found a workaround for this issue:

**Comment by Skyyblaze** [comment]
What is the workaround?

**Comment by 7gxycn08** [comment]
> What is the workaround?

Added It on the projects main page.
